# Generated by Django 4.2.3 on 2023-07-12 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.PositiveBigIntegerField()),
                ('mobile_operator_code', models.PositiveSmallIntegerField()),
                ('tag', models.CharField(max_length=100)),
                ('time_zone', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Mailing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('text', models.TextField()),
                ('client_filter', models.JSONField()),
                ('finish_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_time', models.DateTimeField()),
                ('status', models.CharField(choices=[('SENT', 'Отправлено'), ('PENDING', 'Ожидание отправки'), ('EXPIRED', 'Время отправки истекло'), ('ERROR', 'Ошибка отправки')], default='PENDING', max_length=30)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='notification_app.client')),
                ('mailing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='notification_app.mailing')),
            ],
        ),
    ]
