# Generated by Django 4.2.3 on 2023-07-16 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification_app', '0002_alter_message_sent_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='status',
            field=models.CharField(choices=[('SENT', 'Отправлено'), ('PENDING', 'Ожидание отправки'), ('EXPIRED', 'Время отправки истекло'), ('ERROR', 'Ошибка отправки'), ('PROCESSING', 'В работе (отправка)')], default='PENDING', max_length=30),
        ),
    ]
